### ISSUE TITLE
Love the idea of following a link but would be nice to give links numbers to refer too

### ISSUE THREAD

**Issue by totijack** [digital-detox/web-reader#12]
I find it hard to stop the audio at the right time to follow a link through. I'd propose adding numbers to all links? E.g.

1. "Read all links please"
2. WR: "There are 8 links on the page"
3. WR: "Link 1 Lorem ipsum"
4. WR: "Link 2 Etc."
5. .. interrupt talking with CTRL + SPACE
6. "Read link 1 again please"
7. "Follow this link"

**Comment by AurelioDeRosa** [comment]
This is a duplicate of #2.
